name: "Setup ccache"

inputs:
  MATRIX_OS:
    description: ''
    required: true
  MATRIX_ARCH:
    description: ''
    required: true

outputs:
  HOST_CCACHE_DIR:
    description: ''
    value: ${{ steps.configure_ccache_dir_on_host.outputs.HOST_CCACHE_DIR }}

description: ''

runs:
  using: "composite"
  steps:
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2.9
      with:
        key: ${{ inputs.MATRIX_OS }}-${{ inputs.MATRIX_ARCH }}  # Make cache specific to OS
        max-size: "5G"

    - name: Configure ccache dir on host ubuntu
      if: ${{ inputs.MATRIX_OS == 'ubuntu-20.04' }}
      shell: bash -l {0}
      id: configure_ccache_dir_on_host
      run: |
        
        HOST_CCACHE_DIR="$(ccache --get-config cache_dir)"
        mkdir -p $HOST_CCACHE_DIR
        echo "HOST_CCACHE_DIR=$HOST_CCACHE_DIR" | tee -a $GITHUB_OUTPUT

    - name: Configure ccache
      if: ${{ inputs.MATRIX_OS == 'ubuntu-20.04' || inputs.MATRIX_OS == 'macos-11' }}
      shell: bash -l {0}
      run: |
        
        if [ x"${{ inputs.MATRIX_OS }}" == x"macos-11" ]; then
          echo "/usr/local/opt/ccache/libexec" >> $GITHUB_PATH
        else
          echo "/usr/lib/ccache:/usr/lib64/ccache:/usr/lib/ccache/bin" >> $GITHUB_PATH
        fi
